### ISSUE TITLE
Неверный формат date

### ISSUE THREAD

**Issue by mirecl** [Konstantin0804/SberCredit#2]
Необходимо изменить формат значения поля ``date`` на шаблон ``dd.mm.YYYY``.
**Пример (входящий JSON):**
```json
{
  "amount": 10000,
  "date": "31.01.2021",
  "periods": 7,
  "rate": 6.5
}
```
**Пример (исходящий JSON):**
```json
{
  "28.02.2021": 10108.64,
  "30.04.2021": 10218.46,
  "30.06.2021": 10329.46,
  "31.01.2021": 10054.17,
  "31.03.2021": 10163.4,
  "31.05.2021": 10273.81,
  "31.07.2021": 10385.42
}
``` 
Добавить валидацию для этого поля.

**Comment by Konstantin0804** [comment]
Изменил формат поля date на указанный в шаблоне и добавил валидацию входящего JSON череp @pre-load'ер

**Comment by mirecl** [comment]
Поправить swagger - там формат даты старый.

**Comment by Konstantin0804** [comment]
Извиняюсь, упустил момент про исправления в Swagger. Поправил, теперь пример даты там тоже отображается корректный
