### ISSUE TITLE
Добавить поддержку gunicorn

### ISSUE THREAD

**Issue by mirecl** [Konstantin0804/SberCredit#4]
Добавить запуск приложения ``Flask`` с помощью ``gunicorn``.
Подробнее см. https://flask.palletsprojects.com/en/2.0.x/deploying/wsgi-standalone/

**Comment by Konstantin0804** [comment]
Добавлена возможность запуска с gunicorn командой gunicorn app:app. Можно далее переходить в браузере по адресу http://127.0.0.1:8000/credit
