### ISSUE TITLE
Добавить поддержку запуска unit-тестов с помощью pytest

### ISSUE THREAD

**Issue by mirecl** [Konstantin0804/SberCredit#5]
Подробнее см. https://docs.pytest.org/en/6.2.x/unittest.html
Добавить в README.md описание запуска тестов.

**Comment by Konstantin0804** [comment]
Запуск Unittest'ов теперь доступен с командной строки командой python -m unittest. 
Сейчас разбираюсь с pytest, конкретно с ошибкой по не возможность импорта библиотек. Если успею разобраться то оставлю соответствующий комментарий и внесу изменения на git

**Comment by mirecl** [comment]
Главное сделай https://github.com/Konstantin0804/SberCredit/issues/2 и https://github.com/Konstantin0804/SberCredit/issues/1

**Comment by Konstantin0804** [comment]
Пункты с исправлением и валидацией даты и формата amount уже выполнены, репозиторий обновлен, сейчас разбираюсь с Docker'ом, ранее с ним не работал

**Comment by Konstantin0804** [comment]
Запуск unittest'ов через pytest заработал. Доступен со сводным отчетом по команде pytest -rpP tests/test.py
